//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoevolutionMCSNavigatorExperimentEvaluationData
    {
        public int ExperimentDictionaryID { get; set; }
        public int Run { get; set; }
        public int Generation { get; set; }
        public int PopulationSize { get; set; }
        public int ViableOffspringCount { get; set; }
        public int MinComplexity { get; set; }
        public int MaxComplexity { get; set; }
        public double MeanComplexity { get; set; }
        public int TotalEvaluations { get; set; }
        public Nullable<int> EvaluationsPerSecond { get; set; }
    
        public virtual ExperimentDictionary ExperimentDictionary { get; set; }
    }
}
