//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCCFullTrajectory
    {
        public int ExperimentDictionaryID { get; set; }
        public int Run { get; set; }
        public int Generation { get; set; }
        public int Timestep { get; set; }
        public int MazeGenomeID { get; set; }
        public int NavigatorGenomeID { get; set; }
        public decimal XPosition { get; set; }
        public decimal YPosition { get; set; }
    
        public virtual ExperimentDictionary ExperimentDictionary { get; set; }
    }
}
