//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCSExperimentEvaluationData
    {
        public int ExperimentDictionaryID { get; set; }
        public int Run { get; set; }
        public int Generation { get; set; }
        public int PopulationSize { get; set; }
        public int OffspringCount { get; set; }
        public Nullable<int> TotalEvaluations { get; set; }
        public Nullable<int> EvaluationsPerSecond { get; set; }
        public int ClosestGenomeID { get; set; }
        public int ClosestGenomeConnectionGeneCount { get; set; }
        public int ClosestGenomeNeuronGeneCount { get; set; }
        public int ClosestGenomeTotalGeneCount { get; set; }
        public Nullable<int> ClosestGenomeEvaluationCount { get; set; }
        public Nullable<double> ClosestGenomeDistanceToTarget { get; set; }
        public Nullable<double> ClosestGenomeEndPositionX { get; set; }
        public Nullable<double> ClosestGenomeEndPositionY { get; set; }
        public int RunPhase_FK { get; set; }
        public string ClosestGenomeXml { get; set; }
        public int MaxComplexity { get; set; }
        public double MeanComplexity { get; set; }
    
        public virtual ExperimentDictionary ExperimentDictionary { get; set; }
        public virtual RunPhase RunPhase { get; set; }
    }
}
