//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExperimentEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoveltyExperimentEvaluationData
    {
        public int ExperimentDictionaryID { get; set; }
        public int Run { get; set; }
        public int Generation { get; set; }
        public int SpecieCount { get; set; }
        public int AsexualOffspringCount { get; set; }
        public int SexualOffspringCount { get; set; }
        public int TotalOffspringCount { get; set; }
        public int InterspeciesOffspringCount { get; set; }
        public double MaxFitness { get; set; }
        public double MeanFitness { get; set; }
        public double MeanSpecieChampFitness { get; set; }
        public int MaxComplexity { get; set; }
        public double MeanComplexity { get; set; }
        public int MinSpecieSize { get; set; }
        public int MaxSpecieSize { get; set; }
        public Nullable<int> TotalEvaluations { get; set; }
        public Nullable<int> EvaluationsPerSecond { get; set; }
        public int ChampGenomeID { get; set; }
        public double ChampGenomeFitness { get; set; }
        public int ChampGenomeBirthGeneration { get; set; }
        public int ChampGenomeConnectionGeneCount { get; set; }
        public int ChampGenomeNeuronGeneCount { get; set; }
        public int ChampGenomeTotalGeneCount { get; set; }
        public Nullable<int> ChampGenomeEvaluationCount { get; set; }
        public Nullable<double> ChampGenomeBehavior1 { get; set; }
        public Nullable<double> ChampGenomeBehavior2 { get; set; }
    
        public virtual ExperimentDictionary ExperimentDictionary { get; set; }
    }
}
